# frozen_string_literal: true

module GraphqlErrorType
  ARGUMENT_ERROR = "ARGUMENT_ERROR"
  AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
  COMMENT_CREATE_ERROR = "COMMENT_CREATE_ERROR"
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
  POST_CREATE_ERROR = "POST_CREATE_ERROR"
  UNAUTHORIZED = "UNAUTHORIZED"
end
